version: "3.3"
services:
    db:
        image: mysql:8.0
        container_name: aart-mysql 
        restart: always
        volumes:
            - ./mysql-dump:/var/lib/mysql
            - ./mysql-init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: aart
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "3306:3306"
    pma:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: aart-mysql-pma 
        restart: always
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - "8081:80"
    web:
        depends_on:
            - db
        image: tomcat:9.0.10
        container_name: aart-tomcat
        volumes:
            - ./aart.war:/usr/local/tomcat/webapps/aart.war
        restart: always
        ports:
            - "8080:8080"
        environment:
            DATABASE_NAME: aart
